version: '3.8'

services:
  web:
    build: .
    container_name: php_apache
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    environment:
      - DB_HOST=mysql_db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=projeto_dio

  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto_dio
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
